--1-1

SELECT 
	DEPARTMENT_NAME AS 학과명
	, CATEGORY AS 계열
FROM TB_DEPARTMENT ;

--1-2
SELECT 
	DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.'
FROM TB_DEPARTMENT ;

--1-3
SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '001'
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN, 8,1) = '2' ;

-- 1-4
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 1-5
SELECT 
	DEPARTMENT_NAME 
	, CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 1-6
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


-- 1-7
SELECT CLASS_NO 
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 1-8
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;

-- 1-9
SELECT 
	STUDENT_NO 
	, STUDENT_NAME 
	, STUDENT_SSN 
	,STUDENT_ADDRESS
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '%전주%'
AND STUDENT_NO LIKE 'A2%';

---------------------------------------------------------------------------------

-- 2-1

SELECT  
	STUDENT_NO AS 학번
	, STUDENT_NAME AS 이름
	, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD')  AS 입학년도
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

-- 2-2
SELECT 
	PROFESSOR_NAME
	, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != '3';


-- 2-3
SELECT 
	PROFESSOR_NAME AS 교수이름
	, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY') ) - TO_NUMBER('19'||TO_NUMBER(SUBSTR(PROFESSOR_SSN,1,2)))+1 AS 나이
FROM TB_PROFESSOR
ORDER BY  나이 ASC;

-- 2-4
SELECT SUBSTR(PROFESSOR_NAME,2,3)  
FROM TB_PROFESSOR;

-- 2-5
SELECT 
	STUDENT_NO 
	, STUDENT_NAME 
FROM TB_STUDENT
WHERE 19||SUBSTR(STUDENT_SSN,1,2)+19 < EXTRACT(YEAR FROM ENTRANCE_DATE) ;

-- 2-6
SELECT 
	STUDENT_NO
	, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE ('A%');

-- 2-7
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE 
WHERE STUDENT_NO = 'A517178';

-- 2-8
SELECT S.DEPARTMENT_NO , COUNT(S.DEPARTMENT_NO) 
FROM TB_STUDENT S
GROUP BY S.DEPARTMENT_NO  
ORDER BY S.DEPARTMENT_NO ;

-- 2-9
SELECT COUNT(*)
FROM TB_STUDENT 
WHERE COACH_PROFESSOR_NO  IS NULL;

-- 2-10
SELECT 
	SUBSTR(S.TERM_NO,1,4) AS 년도  
	,ROUND(AVG(POINT),1) AS "년도 별 평점" 
FROM TB_GRADE S
WHERE S.STUDENT_NO = 'A112113'
GROUP BY SUBSTR(S.TERM_NO,1,4) 
ORDER BY SUBSTR(S.TERM_NO,1,4) 
;

-- 2-11
SELECT 
	DEPARTMENT_NO AS "학과코드 명"
	, COUNT(DECODE(ABSENCE_YN,'N', NULL, 1))  AS "휴학생 수"
--SELECT DEPARTMENT_NO, SUM(DECODE(ABSENCE_YN,'N', 0, 1)) 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


-- 2-12
SELECT 
	STUDENT_NAME AS 동일이름
	, COUNT(*) AS "동명인 수" 
FROM TB_STUDENT 
GROUP BY STUDENT_NAME 
HAVING COUNT(*) <> 1 ;

-- 2-13
SELECT 
	NVL(SUBSTR(TERM_NO, 1,4), ' ') AS 년도
	, NVL(SUBSTR(TERM_NO, 5,2),' ') AS 학기
	, ROUND( AVG(POINT),1) AS 평점
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO, 1,4),SUBSTR(TERM_NO, 5,2)) ;

-- 3-1
SELECT STUDENT_NAME , STUDENT_ADDRESS 
FROM TB_STUDENT 
ORDER BY STUDENT_NAME ASC;

-- 3-2
SELECT STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3-3
SELECT S.STUDENT_NAME AS "학생이름" ,  G.STUDENT_NO AS "학번" , S.STUDENT_ADDRESS AS "거주지 주소" 
FROM TB_STUDENT S 
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE S.STUDENT_NO LIKE '9%'	
AND (S.STUDENT_ADDRESS LIKE '%강원도%'
OR S.STUDENT_ADDRESS LIKE '%경기도%')
GROUP BY S.STUDENT_NAME, G.STUDENT_NO, S.STUDENT_ADDRESS
ORDER BY S.STUDENT_NAME, G.STUDENT_NO , S.STUDENT_ADDRESS ASC;


-- 3-4
SELECT PROFESSOR_NAME , PROFESSOR_SSN , PROFESSOR_NO
FROM TB_PROFESSOR P
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '법학과'
ORDER BY P.PROFESSOR_SSN ASC;

-- 3-5
SELECT S.STUDENT_NO, TRIM(BOTH ' ' FROM TO_CHAR(G.POINT,'FM9.00')) AS 학점
FROM TB_STUDENT S 
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE CLASS_NO = 'C3118100'
AND TERM_NO = '200402'
ORDER BY POINT DESC , S.STUDENT_NO ASC ; 

-- 3-6
SELECT S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY S.STUDENT_NAME ASC ;

-- 3-7
SELECT C.CLASS_NAME , D.DEPARTMENT_NAME 
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO);

-- 3-8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR P
JOIN TB_CLASS_PROFESSOR CP ON (P.PROFESSOR_NO = CP.PROFESSOR_NO)
JOIN TB_CLASS C ON (C.CLASS_NO = CP.CLASS_NO);

-- 3-9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR P ON (C.CLASS_NO = P.CLASS_NO)
JOIN TB_PROFESSOR PRO ON (P.PROFESSOR_NO = PRO.PROFESSOR_NO)
WHERE D.CATEGORY  = '인문사회'
ORDER BY C.CLASS_NAME , PROFESSOR_NAME ASC;

-- 3-10
SELECT 
	 DISTINCT S.STUDENT_NO AS 학번 
	 ,S.STUDENT_NAME 
	 , ROUND(AVG(G.POINT),1) AS "전체 평점" 
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE DEPARTMENT_NO = 059
GROUP BY S.STUDENT_NO, S.STUDENT_NAME
ORDER BY S.STUDENT_NO ;

-- 3-11
SELECT D.DEPARTMENT_NAME AS 학과이름, S.STUDENT_NAME AS 학생이름 ,P.PROFESSOR_NAME AS 지도교수이름
FROM TB_DEPARTMENT D
JOIN TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.STUDENT_NO = 'A313047';


-- 3-12 
SELECT STUDENT_NAME, G.TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE G.CLASS_NO = 'C2604100'
AND SUBSTR(G.TERM_NO,1,4) = 2007 
ORDER BY S.STUDENT_NO ASC ;

-- 3-13

SELECT CLASS_NAME, DEPARTMENT_NAME 
FROM TB_DEPARTMENT D
JOIN TB_CLASS C ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE D.CATEGORY = '예체능'
AND C.CLASS_NO  NOT IN (
	SELECT CLASS_NO 
	FROM TB_CLASS_PROFESSOR
);

-- 3-14
SELECT STUDENT_NAME AS "학생이름", NVL(P.PROFESSOR_NAME , '지도교수 미지정') AS "지도교수"
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.DEPARTMENT_NO = 020
ORDER BY S.STUDENT_NO ASC;

-- 3-15
SELECT S.STUDENT_NO , S.STUDENT_NAME ,D.DEPARTMENT_NAME , AVG(POINT)
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME,D.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4 
ORDER BY S.STUDENT_NO 
;

-- 3-16
SELECT C.CLASS_NO , C.CLASS_NAME , TRUNC(AVG(G.POINT), 2) 
FROM TB_CLASS C
JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
WHERE C.DEPARTMENT_NO  = 034
AND C.CLASS_TYPE = '전공선택'
GROUP BY C.CLASS_NO , C.CLASS_NAME 
ORDER BY CLASS_NO ;

-- 3-17
SELECT STUDENT_NAME , STUDENT_ADDRESS 
FROM TB_STUDENT S 
WHERE DEPARTMENT_NO =(
	SELECT DEPARTMENT_NO 
	FROM TB_STUDENT S2
	WHERE S2.STUDENT_NAME = '최경희'
);


-- 3-18

SELECT S.STUDENT_NO , S.STUDENT_NAME 
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE 
	S.DEPARTMENT_NO = 001
GROUP BY S.STUDENT_NO , S.STUDENT_NAME 
HAVING AVG(G.POINT) = (
	SELECT MAX(AVG(G2.POINT))	
	FROM TB_STUDENT S2
	JOIN TB_GRADE G2 ON (S2.STUDENT_NO = G2.STUDENT_NO)
	WHERE S2.DEPARTMENT_NO = 001
	GROUP BY S2.DEPARTMENT_NO, S2.STUDENT_NO , S2.STUDENT_NAME  
) ;

-- 3-19

SELECT D.DEPARTMENT_NAME AS "계열 학과명" ,ROUND(AVG(G.POINT),1) AS "전공평점" 
FROM TB_CLASS C
JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.CATEGORY ='자연과학'
AND C.CLASS_TYPE LIKE '%전공%'
GROUP BY D.DEPARTMENT_NAME 
ORDER BY DEPARTMENT_NAME
;

-- 환경 조경학과 DEPARTMENT_NO = 034, CATEGORY = '자연과학'

