--1-1

SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열
FROM TB_DEPARTMENT ;

--1-2
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.'
FROM TB_DEPARTMENT ;

--1-3
SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '001'
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN, 8,1) = '2' ;

-- 1-4
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 1-5
SELECT DEPARTMENT_NAME , CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 1-6
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


-- 1-7
SELECT CLASS_NO 
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 1-8
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;

-- 1-9
SELECT STUDENT_NO , STUDENT_NAME , STUDENT_SSN ,STUDENT_ADDRESS
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '%전주%'
AND STUDENT_NO LIKE 'A2%';

---------------------------------------------------------------------------------

-- 2-1

SELECT  STUDENT_NO AS 학번, STUDENT_NAME AS 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD')  AS 입학년도
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

-- 2-2
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != '3';


-- 2-3
SELECT PROFESSOR_NAME AS 교수이름, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY') ) - TO_NUMBER('19'||TO_NUMBER(SUBSTR(PROFESSOR_SSN,1,2)))+1 AS 나이
FROM TB_PROFESSOR
ORDER BY  나이 ASC;

-- 2-4
SELECT SUBSTR(PROFESSOR_NAME,2,3)  
FROM TB_PROFESSOR;

-- 2-5
SELECT STUDENT_NO , STUDENT_NAME ,TO_CHAR(SYSDATE,'YYYY') - TO_NUMBER('19'||SUBSTR(STUDENT_SSN,1,2)), SUBSTR(TO_CHAR(ENTRANCE_DATE, 'YYYY'),1,2)
 FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,2,3) != SUBSTR(TO_CHAR(ENTRANCE_DATE, 'YYYY'),1,2)


